### ISSUE TITLE
Error when running zappa status dev

### ISSUE THREAD

**Issue by vsem-cinch** [CiscoSecurity/tr-05-serverless-have-i-been-pwned#23]
Hi I get the following error when I run zappa status dev after following all the steps. I even tried to run zappa init and it asked me where my your_module.app and I could not find that anywhere. Thanks

(Werkzeug 1.0.1 (/Users/vsem/venv/lib/python3.7/site-packages), Requirement.parse('Werkzeug<1.0'), {'zappa'})
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/vsem/venv/lib/python3.7/site-packages/zappa/cli.py", line 2778, in handle
    sys.exit(cli.handle())
  File "/Users/vsem/venv/lib/python3.7/site-packages/zappa/cli.py", line 491, in handle
    self.load_settings_file(self.vargs.get('settings_file'))
  File "/Users/vsem/venv/lib/python3.7/site-packages/zappa/cli.py", line 2180, in load_settings_file
    settings_file = self.get_json_or_yaml_settings()
  File "/Users/vsem/venv/lib/python3.7/site-packages/zappa/cli.py", line 2160, in get_json_or_yaml_settings
    raise ClickException("Please configure a zappa_settings file or call `zappa init`.")
click.exceptions.ClickException: Please configure a zappa_settings file or call `zappa init`.

**Comment by gdavoian** [comment]
Please make sure that `zappa_settings.json` is in the working directory (i.e. the directory where you are running the command).

Otherwise, you have to explicitly specify the path to your settings file: `zappa status dev --settings_file <path/to/your/settings/file>`
